version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    ports: 
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
  frontend:
    build:
      context: ./front-end
      dockerfile: ./front-end.dockerfile
    restart: always
    ports: 
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1